/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import controlador.validaciones;
import javax.swing.JOptionPane;

/**
 *
 * @author Sephi
 */
public class CrearCurso extends javax.swing.JFrame {

    /**
     * Creates new form CrearCursoFrame
     */
    private String[] cursos = {};  
    
    public CrearCurso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GuardarBoton = new javax.swing.JButton();
        OpcionesAvanzadasBoton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        numeroGrupoPanelTexto = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        CodigoCursoPanelTexto = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        cupoPanelTexto = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        asistente2 = new javax.swing.JTextPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        asistente1 = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        profesor = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        nombreCurso = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        descripcion = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BuscarCursoComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        Archivo = new javax.swing.JMenu();
        itmInicio = new javax.swing.JMenuItem();
        itmSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(750, 553));
        getContentPane().setLayout(null);

        GuardarBoton.setText("Guardar");
        GuardarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarBotonActionPerformed(evt);
            }
        });
        getContentPane().add(GuardarBoton);
        GuardarBoton.setBounds(290, 440, 110, 30);

        OpcionesAvanzadasBoton.setText("Opciones Avanzadas");
        OpcionesAvanzadasBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcionesAvanzadasBotonActionPerformed(evt);
            }
        });
        getContentPane().add(OpcionesAvanzadasBoton);
        OpcionesAvanzadasBoton.setBounds(70, 440, 160, 30);

        jScrollPane4.setViewportView(numeroGrupoPanelTexto);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(140, 150, 50, 30);

        jScrollPane1.setViewportView(CodigoCursoPanelTexto);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(68, 109, 100, 30);

        jScrollPane5.setViewportView(cupoPanelTexto);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(140, 190, 50, 30);

        jScrollPane8.setViewportView(asistente2);

        getContentPane().add(jScrollPane8);
        jScrollPane8.setBounds(310, 260, 373, 30);

        jScrollPane9.setViewportView(asistente1);

        getContentPane().add(jScrollPane9);
        jScrollPane9.setBounds(310, 220, 373, 30);

        jLabel6.setText("Profesor:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(226, 185, 80, 14);

        jLabel7.setText("Asistente:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(229, 230, 80, 14);

        jLabel8.setText("Asistente:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(229, 270, 80, 20);

        jLabel9.setText("Ingrese los correos");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(312, 149, 170, 14);

        jLabel10.setText("Cupo:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(90, 200, 70, 14);

        jScrollPane7.setViewportView(profesor);

        getContentPane().add(jScrollPane7);
        jScrollPane7.setBounds(312, 177, 373, 30);

        jScrollPane2.setViewportView(nombreCurso);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(230, 110, 428, 30);

        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 90, 200, 14);

        descripcion.setColumns(20);
        descripcion.setRows(5);
        jScrollPane6.setViewportView(descripcion);

        getContentPane().add(jScrollPane6);
        jScrollPane6.setBounds(70, 310, 617, 120);

        jLabel2.setText("Código:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(68, 89, 100, 14);

        jLabel3.setText("Número de grupo:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 160, 130, 14);

        BuscarCursoComboBox.setModel(new javax.swing.DefaultComboBoxModel(cursos));
        BuscarCursoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarCursoComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(BuscarCursoComboBox);
        BuscarCursoComboBox.setBounds(520, 20, 170, 30);

        jLabel4.setText("Cupo:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(124, 109, 29, 14);

        jLabel5.setText("Descripción:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 290, 110, 14);

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.jpg"))); // NOI18N
        lblFondo.setText("jLabel11");
        lblFondo.setPreferredSize(new java.awt.Dimension(759, 553));
        getContentPane().add(lblFondo);
        lblFondo.setBounds(0, 0, 740, 550);

        Archivo.setText("Archivo");

        itmInicio.setText("Menú Principal");
        itmInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmInicioActionPerformed(evt);
            }
        });
        Archivo.add(itmInicio);

        itmSalir.setText("Salir");
        itmSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmSalirActionPerformed(evt);
            }
        });
        Archivo.add(itmSalir);

        jMenuBar.add(Archivo);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarBotonActionPerformed
        // TODO add your handling code here:
        
        validaciones validar = new validaciones();
        
        //Mediante este ciclo se valida que no existan campos te texto vacíos
        if(validar.esVacio(CodigoCursoPanelTexto.getText())==true || validar.esVacio(nombreCurso.getText())==true || 
                         validar.esVacio(numeroGrupoPanelTexto.getText())==true || validar.esVacio(cupoPanelTexto.getText())==true || 
                         validar.esVacio(profesor.getText())==true || validar.esVacio(asistente1.getText())==true || 
                         validar.esVacio(asistente2.getText())==true || validar.esVacio(descripcion.getText())==true ){
            
            JOptionPane.showMessageDialog(this, "Debe completar todos los campos solicitados");            
        }
        else{              
                CodigoCursoPanelTexto.setText(" ");
                nombreCurso.setText(" ");
                numeroGrupoPanelTexto.setText(" ");
                cupoPanelTexto.setText(" ");
                profesor.setText(" ");
                asistente1.setText(" ");
                asistente2.setText(" ");
                descripcion.setText(" ");
                JOptionPane.showMessageDialog(this, "El curso se registro con éxito");                            
        }
    }//GEN-LAST:event_GuardarBotonActionPerformed

    private void OpcionesAvanzadasBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcionesAvanzadasBotonActionPerformed
        // TODO add your handling code here:
        EliminarCurso eliminarCurso = new EliminarCurso();
        eliminarCurso.setVisible(true);
        dispose();
    }//GEN-LAST:event_OpcionesAvanzadasBotonActionPerformed

    private void BuscarCursoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarCursoComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarCursoComboBoxActionPerformed

    private void itmInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmInicioActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu();
        menu.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_itmInicioActionPerformed

    private void itmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_itmSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearCurso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Archivo;
    private javax.swing.JComboBox BuscarCursoComboBox;
    private javax.swing.JTextPane CodigoCursoPanelTexto;
    private javax.swing.JButton GuardarBoton;
    private javax.swing.JButton OpcionesAvanzadasBoton;
    private javax.swing.JTextPane asistente1;
    private javax.swing.JTextPane asistente2;
    private javax.swing.JTextPane cupoPanelTexto;
    private javax.swing.JTextArea descripcion;
    private javax.swing.JMenuItem itmInicio;
    private javax.swing.JMenuItem itmSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JTextPane nombreCurso;
    private javax.swing.JTextPane numeroGrupoPanelTexto;
    private javax.swing.JTextPane profesor;
    // End of variables declaration//GEN-END:variables
}
