/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

/**
 *
 * @author esporras
 */
public class Curso extends javax.swing.JFrame {
    
   

    /**
     * Creates new form Curso
     */
    public Curso() {
        initComponents();
        setBounds(150,100,750,600);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCrearCurso = new javax.swing.JButton();
        btnMatricularCurso = new javax.swing.JButton();
        ScrollTablaCursos = new javax.swing.JScrollPane();
        tablaCursos = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        lblTitulo = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jMenuBar = new javax.swing.JMenuBar();
        Matricular = new javax.swing.JMenu();
        itmInicio = new javax.swing.JMenuItem();
        itmSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(750, 600));
        getContentPane().setLayout(null);

        btnCrearCurso.setText("Crear Curso");
        btnCrearCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCursoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrearCurso);
        btnCrearCurso.setBounds(180, 310, 150, 30);

        btnMatricularCurso.setText("Exportar Datos a CSV");
        getContentPane().add(btnMatricularCurso);
        btnMatricularCurso.setBounds(455, 310, 150, 30);

        tablaCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"PAM-2001", "Computación 1"},
                {"PAM-2002", "Computación 2"},
                {"PAM-2003", "Computación 3"}
            },
            new String [] {
                "Código del Curso", "Nombre del Curso"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaCursos.setToolTipText("");
        ScrollTablaCursos.setViewportView(tablaCursos);

        getContentPane().add(ScrollTablaCursos);
        ScrollTablaCursos.setBounds(110, 160, 540, 80);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 102, 740, 10);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Cursos PAMTEC");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(0, 0, 740, 100);

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.jpg"))); // NOI18N
        lblFondo.setText("jLabel4");
        getContentPane().add(lblFondo);
        lblFondo.setBounds(0, -60, 740, 620);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 0, 0, 2);

        jMenuBar.setPreferredSize(new java.awt.Dimension(49, 25));

        Matricular.setText("Archivo");
        Matricular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatricularActionPerformed(evt);
            }
        });

        itmInicio.setText("Menú Principal");
        itmInicio.setActionCommand("");
        itmInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itmInicioMouseClicked(evt);
            }
        });
        itmInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmInicioActionPerformed(evt);
            }
        });
        Matricular.add(itmInicio);
        itmInicio.getAccessibleContext().setAccessibleDescription("");

        itmSalir.setText("Salir");
        itmSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itmSalirMouseClicked(evt);
            }
        });
        itmSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmSalirActionPerformed(evt);
            }
        });
        Matricular.add(itmSalir);

        jMenuBar.add(Matricular);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MatricularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatricularActionPerformed
        // TODO add your handling code here:

        Matricular matricular = new Matricular();
        matricular.setVisible(true);
        System.out.println("estoy aquí");

    }//GEN-LAST:event_MatricularActionPerformed

    private void btnCrearCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCursoActionPerformed
        // TODO add your handling code here:
        CrearCurso crearCurso = new CrearCurso();
        crearCurso.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCrearCursoActionPerformed

    private void itmInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmInicioActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu();
        menu.setVisible(true);
        
        dispose();
        
    }//GEN-LAST:event_itmInicioActionPerformed

    private void itmInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itmInicioMouseClicked
        // TODO add your handling code here:
        

        
        
    }//GEN-LAST:event_itmInicioMouseClicked

    private void itmSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itmSalirMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_itmSalirMouseClicked

    private void itmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_itmSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Curso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Curso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Curso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Curso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Curso().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Matricular;
    private javax.swing.JScrollPane ScrollTablaCursos;
    private javax.swing.JButton btnCrearCurso;
    private javax.swing.JButton btnMatricularCurso;
    private javax.swing.JMenuItem itmInicio;
    private javax.swing.JMenuItem itmSalir;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tablaCursos;
    // End of variables declaration//GEN-END:variables
}
