/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

/**
 *
 * @author esporras
 */
public class Curso extends javax.swing.JFrame {
    
   

    /**
     * Creates new form Curso
     */
    public Curso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCrearCurso = new javax.swing.JButton();
        btnMatricularCurso = new javax.swing.JButton();
        ScrollTablaCursos = new javax.swing.JScrollPane();
        tablaCursos = new javax.swing.JTable();
        lblFondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Matricular = new javax.swing.JMenu();
        Cursos = new javax.swing.JMenu();
        Colaboladores = new javax.swing.JMenu();
        Salir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(750, 600));
        getContentPane().setLayout(null);

        btnCrearCurso.setText("Crear Curso");
        btnCrearCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCursoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrearCurso);
        btnCrearCurso.setBounds(570, 43, 140, 30);

        btnMatricularCurso.setText("Matricular Curso");
        getContentPane().add(btnMatricularCurso);
        btnMatricularCurso.setBounds(100, 390, 150, 30);

        tablaCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"PAM-2001", "Computación 1"},
                {"PAM-2002", "Computación 2"},
                {"PAM-2003", "Computación 3"}
            },
            new String [] {
                "Código del Curso", "Nombre del Curso"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaCursos.setToolTipText("");
        ScrollTablaCursos.setViewportView(tablaCursos);

        getContentPane().add(ScrollTablaCursos);
        ScrollTablaCursos.setBounds(110, 160, 540, 80);

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.jpg"))); // NOI18N
        lblFondo.setText("jLabel4");
        getContentPane().add(lblFondo);
        lblFondo.setBounds(0, -60, 740, 620);

        Matricular.setText("Matricular");
        Matricular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatricularActionPerformed(evt);
            }
        });
        jMenuBar1.add(Matricular);

        Cursos.setText("Cursos");
        jMenuBar1.add(Cursos);

        Colaboladores.setText("Colaboradores");
        jMenuBar1.add(Colaboladores);

        Salir.setText("Salir");
        jMenuBar1.add(Salir);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MatricularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatricularActionPerformed
        // TODO add your handling code here:

        Matricular matricular = new Matricular();
        matricular.setVisible(true);
        System.out.println("estoy aquí");

    }//GEN-LAST:event_MatricularActionPerformed

    private void btnCrearCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCursoActionPerformed
        // TODO add your handling code here:
        CrearCurso crearCurso = new CrearCurso();
        crearCurso.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCrearCursoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Curso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Curso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Curso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Curso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Curso().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Colaboladores;
    private javax.swing.JMenu Cursos;
    private javax.swing.JMenu Matricular;
    private javax.swing.JMenu Salir;
    private javax.swing.JScrollPane ScrollTablaCursos;
    private javax.swing.JButton btnCrearCurso;
    private javax.swing.JButton btnMatricularCurso;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JTable tablaCursos;
    // End of variables declaration//GEN-END:variables
}
