/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import controlador.validaciones;
/**
 *
 * @author Sephi
 */
public class EliminarCurso extends javax.swing.JFrame {

    /**
     * Creates new form EliminarCurso
     */
    public EliminarCurso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        EliminarBoton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        codigoCursoPanelTexto = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        numeroGrupoCursoPanelTexto = new javax.swing.JTextPane();
        consultarBoton = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 51));
        setPreferredSize(new java.awt.Dimension(256, 216));
        getContentPane().setLayout(null);

        jLabel2.setText("Código:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 80, 100, 14);

        jLabel3.setText("Número grupo:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 110, 100, 14);

        EliminarBoton.setText("Eliminar");
        EliminarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarBotonActionPerformed(evt);
            }
        });
        getContentPane().add(EliminarBoton);
        EliminarBoton.setBounds(140, 160, 90, 23);

        jScrollPane1.setViewportView(codigoCursoPanelTexto);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(120, 80, 100, 22);

        jScrollPane2.setViewportView(numeroGrupoCursoPanelTexto);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(120, 110, 100, 22);

        consultarBoton.setText("Consultar");
        consultarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarBotonActionPerformed(evt);
            }
        });
        getContentPane().add(consultarBoton);
        consultarBoton.setBounds(20, 160, 90, 23);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Eliminar Grupo");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(0, 20, 260, 30);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 60, 260, 10);

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.jpg"))); // NOI18N
        lblFondo.setText("jLabel4");
        getContentPane().add(lblFondo);
        lblFondo.setBounds(0, 0, 260, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EliminarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarBotonActionPerformed
        // TODO add your handling code here:
        validaciones v = new validaciones();
        if(!v.esVacio(codigoCursoPanelTexto.getText().trim()))
        {
        } else {
            
        }
    }//GEN-LAST:event_EliminarBotonActionPerformed

    private void consultarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarBotonActionPerformed
        // TODO add your handling code here:
        Informacion in = new Informacion();
        in.setVisible(true);
    }//GEN-LAST:event_consultarBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EliminarCurso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EliminarBoton;
    private javax.swing.JTextPane codigoCursoPanelTexto;
    private javax.swing.JButton consultarBoton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextPane numeroGrupoCursoPanelTexto;
    // End of variables declaration//GEN-END:variables
}
