/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

/**
 *
 * @author esporras
 */
public class InformacionCurso extends javax.swing.JFrame {

    /**
     * Creates new form InformaciónCurso
     */
    public InformacionCurso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInformacionCurso = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaInfoCursos = new javax.swing.JTable();
        btnMatriculadosColaboradores = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Matricular = new javax.swing.JMenu();
        Cursos = new javax.swing.JMenu();
        Colaboladores = new javax.swing.JMenu();
        Salir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(750, 600));
        getContentPane().setLayout(null);

        lblInformacionCurso.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblInformacionCurso.setText("Información del Curso");
        getContentPane().add(lblInformacionCurso);
        lblInformacionCurso.setBounds(140, 90, 260, 30);

        TablaInfoCursos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TablaInfoCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Código", null},
                {"Nombre", null},
                {"Fecha de Creación", null},
                {"Cupo", null},
                {"Número de Grupo", null},
                {"Detalle", null}
            },
            new String [] {
                "", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaInfoCursos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(130, 160, 530, 110);

        btnMatriculadosColaboradores.setText("Matriculados y Colaboladores");
        btnMatriculadosColaboradores.setActionCommand("");
        getContentPane().add(btnMatriculadosColaboradores);
        btnMatriculadosColaboradores.setBounds(70, 370, 190, 23);

        btnEditar.setText("Editar");
        getContentPane().add(btnEditar);
        btnEditar.setBounds(490, 370, 130, 23);

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.jpg"))); // NOI18N
        lblFondo.setText("jLabel4");
        getContentPane().add(lblFondo);
        lblFondo.setBounds(0, -60, 740, 620);

        Matricular.setText("Matricular");
        Matricular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatricularActionPerformed(evt);
            }
        });
        jMenuBar1.add(Matricular);

        Cursos.setText("Cursos");
        jMenuBar1.add(Cursos);

        Colaboladores.setText("Colaboradores");
        jMenuBar1.add(Colaboladores);

        Salir.setText("Salir");
        jMenuBar1.add(Salir);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MatricularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatricularActionPerformed
        // TODO add your handling code here:

        Matricular matricular = new Matricular();
        matricular.setVisible(true);
        System.out.println("estoy aquí");
    }//GEN-LAST:event_MatricularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacionCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacionCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacionCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacionCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacionCurso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Colaboladores;
    private javax.swing.JMenu Cursos;
    private javax.swing.JMenu Matricular;
    private javax.swing.JMenu Salir;
    private javax.swing.JTable TablaInfoCursos;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnMatriculadosColaboradores;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblInformacionCurso;
    // End of variables declaration//GEN-END:variables
}
