/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import javax.swing.table.DefaultTableModel;
import controlador.Controlador;

/**
 *
 * @author Sephi
 */
public class ListadoMatriculados extends javax.swing.JFrame {

    /**
     * Creates new form ListadoMatriculados
     */
    private String[] nombreColumnas = {"Apellidos","Nombre","Telefono","Telefono"};
    private String[][] datos = {} ;
    
    DefaultTableModel dtm = new DefaultTableModel(datos, nombreColumnas);
    

    
    public ListadoMatriculados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        demastricularBoton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaInscritos = new javax.swing.JTable();
        exportarExcelBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 51));
        getContentPane().setLayout(null);

        demastricularBoton.setText("Desmatricular");
        demastricularBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                demastricularBotonActionPerformed(evt);
            }
        });
        getContentPane().add(demastricularBoton);
        demastricularBoton.setBounds(590, 433, 97, 23);

        listaInscritos.setModel(dtm);
        jScrollPane2.setViewportView(listaInscritos);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(53, 140, 634, 282);

        exportarExcelBoton.setText("Exportar a Excel");
        exportarExcelBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportarExcelBotonActionPerformed(evt);
            }
        });
        getContentPane().add(exportarExcelBoton);
        exportarExcelBoton.setBounds(53, 433, 111, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exportarExcelBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportarExcelBotonActionPerformed
        // TODO add your handling code here:
        Controlador con = new Controlador();
        con.exportarExcel(datos);
    }//GEN-LAST:event_exportarExcelBotonActionPerformed

    private void demastricularBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_demastricularBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_demastricularBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListadoMatriculados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListadoMatriculados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListadoMatriculados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListadoMatriculados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListadoMatriculados().setVisible(true);
            }
        });
    }
    
    public void setDatos(String[][] pDatos)
    {
        datos=pDatos;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton demastricularBoton;
    private javax.swing.JButton exportarExcelBoton;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable listaInscritos;
    // End of variables declaration//GEN-END:variables
}
