/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import controlador.Controlador;
import java.awt.PopupMenu;
import javax.swing.JFrame;

/**
 *
 * @author esporras
 */
public class Menu extends javax.swing.JFrame {

    
    PopupMenu matricular;
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        
        setResizable(false);
        setBounds(150, 100, 750, 600);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        lblFondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Matricular = new javax.swing.JMenu();
        Cursos = new javax.swing.JMenu();
        Colaboladores = new javax.swing.JMenu();
        Salir = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú Principal");
        setPreferredSize(new java.awt.Dimension(750, 600));
        getContentPane().setLayout(null);

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoMenu.jpg"))); // NOI18N
        lblFondo.setText("jLabel4");
        getContentPane().add(lblFondo);
        lblFondo.setBounds(0, -50, 740, 600);

        jMenuBar1.setPreferredSize(new java.awt.Dimension(224, 25));

        Matricular.setText("Matricular");
        Matricular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MatricularMouseClicked(evt);
            }
        });
        Matricular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatricularActionPerformed(evt);
            }
        });
        jMenuBar1.add(Matricular);

        Cursos.setText("Cursos");
        Cursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CursosMouseClicked(evt);
            }
        });
        jMenuBar1.add(Cursos);

        Colaboladores.setText("Colaboradores");
        Colaboladores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ColaboladoresMouseClicked(evt);
            }
        });
        jMenuBar1.add(Colaboladores);

        Salir.setText("Salir");
        jMenuBar1.add(Salir);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MatricularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatricularActionPerformed
        // TODO add your handling code here:
              
   
        
    }//GEN-LAST:event_MatricularActionPerformed

    private void MatricularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MatricularMouseClicked
        // TODO add your handling code here:
            Matricular matricular = new Matricular();
            matricular.setVisible(true);
            dispose();                     
    }//GEN-LAST:event_MatricularMouseClicked

    private void CursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CursosMouseClicked
        // TODO add your handling code here:
        Curso curso = new Curso();
        curso.setVisible(true);
        dispose();
    }//GEN-LAST:event_CursosMouseClicked

    private void ColaboladoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ColaboladoresMouseClicked
        // TODO add your handling code here:
        
        //listar los colaboradores existentes
         dispose();
        Controlador listaColaboradores = new Controlador();        
        
        Colaborador colaborador = new Colaborador();
        colaborador.setVisible(true);
      
        colaborador.setColaborador(listaColaboradores.listarColaboradores());//enviar la lista de colaboradores        
        
       
    }//GEN-LAST:event_ColaboladoresMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Colaboladores;
    private javax.swing.JMenu Cursos;
    private javax.swing.JMenu Matricular;
    private javax.swing.JMenu Salir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lblFondo;
    // End of variables declaration//GEN-END:variables
}
